[package]
edition = "2021"
name = "history"
version = "0.1.0"

[profile.release]
opt-level = "z"
lto = true
overflow-checks = true


[dependencies]
unicode-width = "0.1.9"
unicode-segmentation = "1.9.0"
anyhow = { version = "1.0.58", features = ["backtrace"] }
bincode = "1.3.3"
chrono = "0.4.19"
chronoutil = "0.2.3"
chrono-english = "0.1.7"
glob = "0.3.0"
crossterm = "0.25.0"
daemonize = "0.4.1"
futures-util = "0.3.21"
git-version = "0.3.5"
gethostname = "0.2.3"
lazy_static = "1.4.0"
libc = "0.2.126"
nix = "0.25.0"
rusqlite = { version = "0.28.0", features = ["bundled"] }
serde = { version = "1.0.137", features = ["derive"] }
# structopt = "0.3.26"
clap = { version = "3.2.5", features = ["derive"] }
stybulate = "1.1.2"
sysinfo = { version = "0.26.2", default-features = false, features = [] }
tarpc = { version = "0.30.0", features = ["tcp", "serde-transport-bincode", "serde-transport"] }
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["full", "tracing"] }
tracing = "0.1.35"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
