[package]
edition = "2021"
name = "history"
version = "0.1.0"

[profile.release]
opt-level = "z"
lto = true
overflow-checks = true


[dependencies]
unicode-width = "*"
unicode-segmentation = "1.9.0"
anyhow = {version = "*", features = ["backtrace"]}
bincode = "*"
chrono = "*"
chronoutil = "*"
chrono-english = "*"
glob = "*"
crossterm = "*"
daemonize = "*"
futures-util = "*"
git-version = "*"
gethostname = "*"
lazy_static = "*"
libc = "*"
nix = "*"
rusqlite = { version = "*", features = ["bundled"] }
serde = {version = "*", features = ["derive"]}
structopt = "*"
stybulate = "*"
sysinfo = {version = "*", default-features = false, features = []}
tarpc = {version = "*", features = ["tcp", "serde-transport-bincode", "serde-transport"]}
thiserror = "*"
tokio = {version = "*", features = ["full", "tracing"]}
tracing = "*"
tracing-appender = "*"
tracing-subscriber = {version = "*", features = ["env-filter"]}
