name: "Test"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  x86-64:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - name: Build
      run: |
        nix build -L
        nix flake check -L
